apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring.eks.vt.dev.quaddemo.co.uk-certificate
spec:
  dnsNames:
  - monitoring.eks.vt.dev.quaddemo.co.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cert-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  secretName: monitoring.eks.vt.dev.quaddemo.co.uk-certificate-secret
  usages:
  - server auth
  - client auth


---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kong.eks.vt.dev.quaddemo.co.uk-certificate
spec:
  dnsNames:
  - kong.eks.vt.dev.quaddemo.co.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cert-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  secretName: kong.eks.vt.dev.quaddemo.co.uk-certificate-secret
  usages:
  - server auth
  - client auth