apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-certificate-alpha
spec:
  dnsNames:
  - monitoring.eks.vt.dev.quaddemo.co.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cert-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  secretName: monitoring-certificate-alpha-secret
  usages:
  - server auth
  - client auth