apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cert-issuer
spec:
  acme:
    email: vibhanshu@quadcorps.co.uk
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-cert-issuer
    solvers:
      - selector:
          dnsZones: 
            - kong.eks.vt.dev.quaddemo.co.uk
            - monitoring.eks.vt.dev.quaddemo.co.uk
        http01:
          ingress:
            ingressClassName: nginx
#        dns01:
#          route53:
#            region: eu-west-2
#            hostedZoneID: Z01950412AQ1SLPQP3SSO
